# Generated by Django 4.0.4 on 2022-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='ID пользователя')),
                ('user_email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('user_login', models.CharField(max_length=50, verbose_name='Логин')),
                ('user_password', models.CharField(max_length=40, verbose_name='Пароль')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
